Fix error
infiniflow/ragflow pull request #3456
Opened 2024-11-18 02:52 UTC by JinHai-CN

### What problem does this PR solve?

1. Update README.md
2. Fix error description in docker/.env

### Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

2024-11-18 04:06 UTC, KevinHuSh approved these changes

2024-11-19 02:12 UTC, yuzhichang approved these changes

2024-11-19 02:12 UTC, writinwaters commented on README_zh.md
> +> Infinity 目前官方并为正式支持在 Linux/arm64 架构下的机器上运行.
```suggestion
> Infinity 目前官方暂未正式支持在 Linux/arm64 架构下的机器上运行.
```

2024-11-19 02:17 UTC, writinwaters requested changes

2024-11-19 02:17 UTC, writinwaters commented on README_ja.md
> +> [！警告]
Use English. Same for the other languages.

2024-11-19 03:31 UTC, merged